spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

## zuul默认地址是 zuul地址+服务名+服务接口

## 自定义路由规则
zuul:
  routes:
    #    myProduct:  #路由规则名
    #      path: /myProduct/** #自定义路由地址
    #      serviceId: product #服务名

    ## 简介写法
    product: /myProduct/**
    # 禁止某个路由地址被访问
  ignored-patterns:
    - /product/product/listForOrder
    - /myProduct/product/listForOrder
  #全局敏感头设置，全部忽略，可传递cookie
  sensitive-headers: